apiVersion: apps/v1
kind: Deployment
metadata:
  name: alibaba-kafka-demo
  namespace: default
  labels:
    app: alibaba-kafka-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alibaba-kafka-demo
  template:
    metadata:
      labels:
        app: alibaba-kafka-demo
    spec:
      containers:
      - name: alibaba-kafka-demo
        image: registry.cn-beijing.aliyuncs.com/kafka-test/alibaba-kafka-demo:latest
        env:
        - name: kafka_server
          value: "192.168.0.53:9092,192.168.0.52:9092,192.168.0.51:9092"
        - name: kafka_topic
          value: kafka-demo-test
        - name: produce_enable
          value: "true"
        - name: consume_enable
          value: "false"

