spring:
  kafka:
    bootstrap-servers: 121.199.59.159:9093,47.97.205.122:9093,47.111.96.104:9093

    properties:
      ssl.truststore.location: /Users/kongming.lrq/sources/aliware-kafka-demos/kafka-java-demo/vpc-ssl/src/main/resources/kafka.client.truststore.jks
      ssl.truststore.password: KafkaOnsClient
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN

    producer:
      retries: 10
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1

    consumer:
      group-id: kongming_test_cg
      enable-auto-commit: false
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 15000



